name: "1. CI"
description: "Automated CI for the demo-cicd-node project"

on:
  workflow_dispatch:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, feature/**]

jobs:
  ci:
    uses: heliomarpm/reusable-actions/.github/workflows/ci.yml@main
