name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: heliomarpm/reusable-actions/.github/workflows/release.yml@main
    with:
      semantic_release_debug_mode: true
      semantic_release_dry_run: true
      strict_conventional_commits: false
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
